name: chicaga-test-on-schedule
on:
  schedule:
    - cron:  '0 20 * * *'

jobs:
  build:
    runs-on: windows-latest # or macos-latest, windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - name: 'npm:install'
        run: npm install
      - name: test
        run: npm test
      - name: Screenshots
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: screens/
      - name: Send mail
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{secrets.EMAIL_USERNAME}}
          password: ${{secrets.EMAIL_PASSWORD}}
          subject: Автотесты сайта завершились с ошибкой
          body: Возможно требуется проверка работоспособности сайта
          to: dba.knight@gmail.com,n.davydova@chicaga.ru
          from: Сайт chicaga.ru
